# activations.py

_ACTIVATION_FUNCTIONS_STRING_ELU = "elu"
_ACTIVATION_FUNCTIONS_STRING_EXPONENTIAL = "exponential"
_ACTIVATION_FUNCTIONS_STRING_GELU = "gelu"
_ACTIVATION_FUNCTIONS_STRING_HARD_SIGMOID = "hard_sigmoid"
_ACTIVATION_FUNCTIONS_STRING_LINEAR = "linear"
_ACTIVATION_FUNCTIONS_STRING_MISH = "mish"
_ACTIVATION_FUNCTIONS_STRING_RELU = "relu"
_ACTIVATION_FUNCTIONS_STRING_SELU = "selu"
_ACTIVATION_FUNCTIONS_STRING_SIGMOID = "sigmoid"
_ACTIVATION_FUNCTIONS_STRING_SOFTMAX = "softmax"
_ACTIVATION_FUNCTIONS_STRING_SOFTPLUS = "softplus"
_ACTIVATION_FUNCTIONS_STRING_SOFTSIGN = "softsign"
_ACTIVATION_FUNCTIONS_STRING_SWISH = "swish"
_ACTIVATION_FUNCTIONS_STRING_TANH = "tanh"


_LIST_OF_ACCEPTABLE_ACTIVATION_FUNCTIONS = [
    _ACTIVATION_FUNCTIONS_STRING_ELU,
    _ACTIVATION_FUNCTIONS_STRING_EXPONENTIAL,
    _ACTIVATION_FUNCTIONS_STRING_GELU,
    _ACTIVATION_FUNCTIONS_STRING_HARD_SIGMOID,
    _ACTIVATION_FUNCTIONS_STRING_LINEAR,
    _ACTIVATION_FUNCTIONS_STRING_MISH,
    _ACTIVATION_FUNCTIONS_STRING_RELU,
    _ACTIVATION_FUNCTIONS_STRING_SELU,
    _ACTIVATION_FUNCTIONS_STRING_SIGMOID,
    _ACTIVATION_FUNCTIONS_STRING_SOFTMAX,
    _ACTIVATION_FUNCTIONS_STRING_SOFTPLUS,
    _ACTIVATION_FUNCTIONS_STRING_SOFTSIGN,
    _ACTIVATION_FUNCTIONS_STRING_SWISH,
    _ACTIVATION_FUNCTIONS_STRING_TANH,
]